version: '3.4'

volumes:
  opsmxdata:
    name: opsmxdata

services:
  oes-db:
    image: opsmxdev/ubi8-autopilot-db:v1.5
    container_name: oes-db
    restart: always
    volumes:
      - opsmxdata:/var/lib/pgsql-pv

  oes-ldap:
    image: skandragon/ldap-testing-db:latest
    container_name: oes-ldap
    restart: always

  redis:
    image: redis
    container_name: redis
    restart: always

  oes-autopilot:
    image: opsmx11/oes-autopilot:v3.0.0-rc1-202009211021
    container_name: oes-autopilot
    restart: always
    volumes:
      - ./autopilot/autopilot-local.properties:/opsmx/conf/autopilot-local.properties
    expose:
      - "8090"
      - "9090"
    links:
      - "oes-db:oes-db"
    depends_on:
      - oes-db

  oes-platform:
    image: opsmx11/oes-platform:v3.0.0-rc1-202009211008
    container_name: oes-platform
    restart: always
    volumes:
      - ./platform/platform-local.yml:/opsmx/conf/platform-local.yml
    expose:
      - "8095"
    links:
      - "oes-db:oes-db"
    depends_on:
      - oes-db

  oes-dashboard:
    image: opsmx11/oes-dashboard:v3.0.0-rc1-202009210948
    container_name: oes-dashboard
    restart: always
    volumes:
      - ./dashboard/dashboard-local.yml:/opsmx/conf/dashboard-local.yml
    expose:
      - "8094"

  oes-sapor:
    image: opsmx11/oes-sapor:v3.0.0-rc1-202009211012
    container_name: oes-sapor
    restart: always
    volumes:
      - ./sapor/application.yml:/opt/opsmx/application.yml
    expose:
      - "8085"
    depends_on:
      - oes-db

  oes-ui:
    image: opsmx11/oes-ui:v3.0.0-rc1-202009210956
    container_name: oes-ui
    restart: always
    volumes:
      - ./ui/app-config.json:/var/www/html/assets/config/app-config.json
    ports:
      - "4200:80"

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    restart: always
    command: ["run", "--server"]

  oes-gate:
    image: opsmx11/oes-gate:v3.0.0-rc1-202009211015
    container_name: oes-gate
    restart: always
    volumes:
      - ./gate/gate.yml:/opt/spinnaker/config/gate.yml
    ports:
      - "8084:8084"
    depends_on:
      - redis
